# http://docs.travis-ci.com/user/languages/go/
language: go

go: 1.9

os:
  - linux

env:
- MYSQL_USER=root
- CURRENT_CI_ENV=travis

matrix:
  include:
    - os: MARIADB-10.0
      addons:
        mariadb: '10.0'
    - os: MARIADB-10.3
      addons:
        mariadb: '10.3'

addons:
  apt:
    packages:
    - git
    - numactl
    - libaio1

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'

install: true

script:
  - script/cibuild

notifications:
  email: false
